name: asl_text_feature
description: A Flutter ASL-to-text camera prototype.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
